# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

build:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    expire_in: 1 day
    paths:
    - node
    - umd

test:
  stage: test
  script:
  - npm install
  - npm run test:quick
  dependencies:
  - build

